[helpers]

[default]
depends = ["zsh","git","vim","vscode","ghostty"]

[shell.files]
"shell/bat.config" = "~/.config/bat/config"
"shell/fd.ignore" = "~/.config/fd/ignore"
"shell/starship" = "~/.config/starship"
"shell/ripgreprc" = "~/.ripgreprc"

[zsh]
depends = ["shell"]

[zsh.files]
# Zsh init files
"zsh/zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.config/zsh/.zshrc"
# Custom env files
"zsh/env.zsh" = "~/.config/zsh/env.zsh"
"zsh/aliases.zsh" = "~/.config/zsh/aliases.zsh"

#"zsh/confd" = "~/.config/zsh/conf.d"
"zsh/functions/rgf" = "~/.config/zsh/functions/rgf"

"zsh/scripts/compinit.zsh" = "~/.config/zsh/scripts/compinit.zsh"
"zsh/scripts/prompt_fallback.zsh" = "~/.config/zsh/scripts/prompt_fallback.zsh"
"zsh/scripts/starship-transient.zsh" = "~/.config/zsh/scripts/starship-transient.zsh"
# Antidote plugins
"zsh/zsh_plugins.txt" = "~/.config/zsh/.zsh_plugins.txt"

[git.files]
"git/config" = "~/.config/git/config"
"git/ignore" = "~/.config/git/ignore"

[vim.files]
"vim/vimrc" = "~/.vimrc"
"vim/plug.vim" = "~/.vim/autoload/plug.vim"

[vscode.files]
"vscode/settings.json" = "~/Library/Application Support/Code/User/settings.json"
"vscode/keybindings.json" = "~/Library/Application Support/Code/User/keybindings.json"
"vscode/vscw" = "~/.local/bin/vscw"

[ghostty.files]
"ghostty/config" = "~/.config/ghostty/config"

[settings]
default_target_type = "automatic"
