"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = '▶▶ '

format = """
[╭─](c-grey)\
$os\
[](bg:c-blue fg:c-grey)\
$directory\
[](fg:c-blue bg:c-green)\
$git_branch\
$git_status\
[](fg:c-green bg:c-grey)\
$docker_context\
$conda\
[ ](fg:c-grey)\
$fill\
[](c-base)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$java\
$python\
[](bg:c-base fg:c-grey)\
$time\
[ ](fg:c-grey)\
$line_break[╰─](c-grey)$character"""

right_format = "$cmd_duration"

palette = 'ansi'

[palettes.ansi]
c-bg = 'black'
c-grey = 'bright-black'
c-dgrey = 'bright-white'
c-base = 'white'
c-blue = 'blue'
c-cyan = 'cyan'
c-green = 'green'
c-purple = 'purple'
c-red = 'red'
c-yellow = 'yellow'

[os]
disabled = false
style = "bg:c-grey fg:c-base"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[directory]
style = "fg:c-bg bg:c-blue"
format = "[ $path]($style)[$read_only ]($read_only_style)"
read_only_style = "fg:c-bg bg:c-blue"
read_only = ""
repo_root_style = "bold fg:c-bg bg:c-blue"
repo_root_format = "[ $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only ]($read_only_style)"
truncation_length = 3
fish_style_pwd_dir_length = 2

[git_branch]
symbol = ""
style = "bg:c-green"
format = '[[ $symbol $branch ](fg:c-bg bg:c-green)]($style)'

[git_status]
style = "bg:c-green"
format = '[[($all_status$ahead_behind )](fg:c-bg bg:c-green)]($style)'
untracked = ""
staged = "+${count}"
modified = "!${count}"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[nodejs]
symbol = ""
style = "bg:c-base"
format = '[[ $symbol( $version) ](fg:c-bg bg:c-base)]($style)'

[c]
symbol = " "
style = "bg:c-base"
format = '[[ $symbol( $version) ](fg:c-bg bg:c-base)]($style)'

[cpp]
symbol = " "
style = "bg:c-base"
format = '[[ $symbol( $version) ](fg:c-bg bg:c-base)]($style)'

[rust]
symbol = ""
style = "bg:c-base"
format = '[[ $symbol( $version) ](fg:c-bg bg:c-base)]($style)'

[golang]
symbol = ""
style = "bg:c-base"
format = '[[ $symbol( $version) ](fg:c-bg bg:c-base)]($style)'

[php]
symbol = ""
style = "bg:c-base"
format = '[[ $symbol( $version) ](fg:c-bg bg:c-base)]($style)'

[java]
symbol = ""
style = "bg:c-base"
format = '[[ $symbol( $version) ](fg:c-bg bg:c-base)]($style)'

[kotlin]
symbol = ""
style = "bg:c-base"
format = '[[ $symbol( $version) ](fg:c-bg bg:c-base)]($style)'

[haskell]
symbol = ""
style = "bg:c-base"
format = '[[ $symbol( $version) ](fg:c-bg bg:c-base)]($style)'

[python]
symbol = ""
style = "bg:c-base"
format = '[[ $symbol( $version) ](fg:c-bg bg:c-base)]($style)'

[docker_context]
symbol = ""
style = "bg:c-grey"
format = '[[ $symbol( $context) ](fg:c-bg bg:c-grey)]($style)'

[conda]
style = "bg:c-grey"
format = '[[ $symbol( $environment) ](fg:c-bg bg:c-grey)]($style)'

[fill]
symbol = " "

[time]
disabled = false
time_format = "%R"
style = "bg:c-grey"
format = '[[  $time](fg:c-bg bg:c-grey)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:c-green)'
error_symbol = '[❯](bold fg:c-red)'
vimcmd_symbol = '[❮](bold fg:c-green)'
vimcmd_replace_one_symbol = '[❮](bold fg:c-purple)'
vimcmd_replace_symbol = '[❮](bold fg:c-purple)'
vimcmd_visual_symbol = '[❮](bold fg:c-yellow)'
