"$schema" = 'https://starship.rs/config-schema.json'

format = "$directory $character"
right_format = "$time"

palette = 'ansi'

[palettes.ansi]
c-bg = 'black'
c-grey = 'bright-black'
c-dgrey = 'bright-white'
c-base = 'white'
c-blue = 'blue'
c-cyan = 'cyan'
c-green = 'green'
c-purple = 'purple'
c-red = 'red'
c-yellow = 'yellow'

[directory]
style = "fg:c-grey"
format = "[$path]($style)"
truncation_length = 3
fish_style_pwd_dir_length = 2

[character]
success_symbol = "[❯](fg:c-green)"
error_symbol = "[❯](fg:c-red)"

[time]
disabled = false
time_format = "%R"
format = " $time"
